-- MySQL Script generated by MySQL Workbench
-- Пт. 01 апр. 2016 23:29:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema medical
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medical` ;

-- -----------------------------------------------------
-- Schema medical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical` DEFAULT CHARACTER SET utf8 ;
USE `medical` ;

-- -----------------------------------------------------
-- Table `medical`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`role` ;

CREATE TABLE IF NOT EXISTS `medical`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`user` ;

CREATE TABLE IF NOT EXISTS `medical`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role`
  FOREIGN KEY (`role_id`)
  REFERENCES `medical`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`department` ;

CREATE TABLE IF NOT EXISTS `medical`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`doctor` ;

CREATE TABLE IF NOT EXISTS `medical`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `secondname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `qualification` VARCHAR(45) NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_user1_idx` (`user_id` ASC),
  INDEX `fk_doctor_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_doctor_user1`
  FOREIGN KEY (`user_id`)
  REFERENCES `medical`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_department1`
  FOREIGN KEY (`department_id`)
  REFERENCES `medical`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`client` ;

CREATE TABLE IF NOT EXISTS `medical`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `secondname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_client_user1`
  FOREIGN KEY (`user_id`)
  REFERENCES `medical`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`schedule` ;

CREATE TABLE IF NOT EXISTS `medical`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workday` VARCHAR(45) NOT NULL,
  `beginworkday` INT NOT NULL,
  `endworkday` INT NOT NULL,
  `room` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_doctor1_idx` (`doctor_id` ASC),
  CONSTRAINT `fk_schedule_doctor1`
  FOREIGN KEY (`doctor_id`)
  REFERENCES `medical`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`medical_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`medical_history` ;

CREATE TABLE IF NOT EXISTS `medical`.`medical_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medical_history_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_medical_history_client1`
  FOREIGN KEY (`client_id`)
  REFERENCES `medical`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`order` ;

CREATE TABLE IF NOT EXISTS `medical`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` INT NOT NULL,
  `begin_time` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_doctor1_idx` (`doctor_id` ASC),
  INDEX `fk_order_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_order_doctor1`
  FOREIGN KEY (`doctor_id`)
  REFERENCES `medical`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_client1`
  FOREIGN KEY (`client_id`)
  REFERENCES `medical`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`visit` ;

CREATE TABLE IF NOT EXISTS `medical`.`visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `complaints` VARCHAR(200) NOT NULL,
  `diagnosys` VARCHAR(100) NOT NULL,
  `medical_history_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visit_medical_history1_idx` (`medical_history_id` ASC),
  INDEX `fk_visit_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_visit_medical_history1`
  FOREIGN KEY (`medical_history_id`)
  REFERENCES `medical`.`medical_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_order1`
  FOREIGN KEY (`order_id`)
  REFERENCES `medical`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`cure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`cure` ;

CREATE TABLE IF NOT EXISTS `medical`.`cure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`treatment` ;

CREATE TABLE IF NOT EXISTS `medical`.`treatment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prescription` VARCHAR(45) NULL,
  `cure_count` INT NOT NULL,
  `method_of_using` VARCHAR(45) NOT NULL,
  `cure_id` INT NOT NULL,
  `visit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_treatment_cure1_idx` (`cure_id` ASC),
  INDEX `fk_treatment_visit1_idx` (`visit_id` ASC),
  CONSTRAINT `fk_treatment_cure1`
  FOREIGN KEY (`cure_id`)
  REFERENCES `medical`.`cure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treatment_visit1`
  FOREIGN KEY (`visit_id`)
  REFERENCES `medical`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical`.`analyse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical`.`analyse` ;

CREATE TABLE IF NOT EXISTS `medical`.`analyse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `result` VARCHAR(200) NOT NULL,
  `doctor_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `visit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_analyse_doctor1_idx` (`doctor_id` ASC),
  INDEX `fk_analyse_client1_idx` (`client_id` ASC),
  INDEX `fk_analyse_visit1_idx` (`visit_id` ASC),
  CONSTRAINT `fk_analyse_doctor1`
  FOREIGN KEY (`doctor_id`)
  REFERENCES `medical`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analyse_client1`
  FOREIGN KEY (`client_id`)
  REFERENCES `medical`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analyse_visit1`
  FOREIGN KEY (`visit_id`)
  REFERENCES `medical`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO  `medical`.`role` (`id`, `name`) VALUES (NULL,  'Admin');
INSERT INTO  `medical`.`role` (`id`, `name`) VALUES (NULL,  'Client');
INSERT INTO  `medical`.`role` (`id`, `name`) VALUES (NULL,  'Doctor');

INSERT INTO  `medical`.`department` (`id`, `name`, `address`) VALUES (NULL,  'Surgery', 'Naberezhnaya, 4');
INSERT INTO  `medical`.`department` (`id`, `name`, `address`) VALUES (NULL,  'Traumatology', 'Naberezhnaya, 5');
INSERT INTO  `medical`.`department` (`id`, `name`, `address`) VALUES (NULL,  'Dentistry', 'Naberezhnaya, 6');

INSERT INTO  `medical`.`cure` (`id`, `name`) VALUES (NULL,  'Aspirin');
INSERT INTO  `medical`.`cure` (`id`, `name`) VALUES (NULL,  'Analgin');
INSERT INTO  `medical`.`cure` (`id`, `name`) VALUES (NULL,  'Paracetamol');

INSERT INTO  `medical`.`user` (`id`, `login`, `password`, `role_id`)
VALUES (NULL ,  'admin',  'adminadmin',  '1');
INSERT INTO  `medical`.`user` (`id`, `login`, `password`, `role_id`)
VALUES (NULL ,  'vitaly',  'vitalyorlov',  '2');
INSERT INTO  `medical`.`user` (`id`, `login`, `password`, `role_id`)
VALUES (NULL ,  'dmitri',  'dmitrisoroko',  '2');
INSERT INTO  `medical`.`user` (`id`, `login`, `password`, `role_id`)
VALUES (NULL ,  'doctor',  'doctordoctor',  '3');
INSERT INTO  `medical`.`user` (`id`, `login`, `password`, `role_id`)
VALUES (NULL ,  'artem',  'artsiomsh',  '3');


INSERT INTO  `medical`.`client` (`id`, `firstname`, `secondname`, `lastname`, `phone_number`, `address`, `email`, `user_id`)
VALUES (NULL ,  'Vitaly',  'Olegovich',  'Orlov',  '+375293338950',  'Lenina, 44',  'vitali11@gmail.com',  '2');
INSERT INTO  `medical`.`client` (`id`, `firstname`, `secondname`, `lastname`, `phone_number`, `address`, `email`, `user_id`)
VALUES (NULL ,  'Dmitrii',  'Batkovich',  'Soroko',  '+375291138950',  'Kosmonavtov, 14',  'sorokod11@gmail.com',  '3');

INSERT INTO  `medical`.`doctor` (`id`, `firstname`, `secondname`, `lastname`, `qualification`,
`speciality`, `phone_number`, `email`, `user_id`, `department_id`)
VALUES (NULL,  'Artem',  'Batkovich',  'Shushkevich',  'doctor',
'surgeon',  '+375298899978',  'artsem@mail.ru',  '4',  '2');
INSERT INTO  `medical`.`doctor` (`id`, `firstname`, `secondname`, `lastname`, `qualification`,
`speciality`, `phone_number`, `email`, `user_id`, `department_id`)
VALUES (NULL,  'Doc',  'Batkovich',  'Doctorovich',  'doctor',
'surgeon',  '+375298119978',  'docdocc@mail.ru',  '5',  '1');

INSERT INTO  `medical`.`medical_history` (`id`, `client_id`)
VALUES (NULL ,  '1');
INSERT INTO  `medical`.`medical_history` (`id`, `client_id`)
VALUES (NULL ,  '2');

INSERT INTO  `medical`.`order` (`id`, `date`, `begin_time`, `doctor_id`, `client_id`)
VALUES (NULL,  '1482278400',  '1482318671',  '1',  '1');
INSERT INTO  `medical`.`order` (`id`, `date`, `begin_time`, `doctor_id`, `client_id`)
VALUES (NULL,  '1482278400',  '1482326400',  '1',  '2');
INSERT INTO  `medical`.`order` (`id`, `date`, `begin_time`, `doctor_id`, `client_id`)
VALUES (NULL,  '1482278400',  '1482318671',  '2',  '1');
INSERT INTO  `medical`.`order` (`id`, `date`, `begin_time`, `doctor_id`, `client_id`)
VALUES (NULL,  '1482278400',  '1482326400',  '2',  '2');

INSERT INTO  `medical`.`visit` (`id`, `complaints`, `diagnosys`, `medical_history_id`, `order_id`)
VALUES (NULL ,  'headache',  'headache',  '1',  '1');
INSERT INTO  `medical`.`visit` (`id`, `complaints`, `diagnosys`, `medical_history_id`, `order_id`)
VALUES (NULL ,  'headache',  'headache',  '1',  '2');
INSERT INTO  `medical`.`visit` (`id`, `complaints`, `diagnosys`, `medical_history_id`, `order_id`)
VALUES (NULL ,  'headache',  'headache',  '2',  '3');
INSERT INTO  `medical`.`visit` (`id`, `complaints`, `diagnosys`, `medical_history_id`, `order_id`)
VALUES (NULL ,  'headache',  'headache',  '2',  '4');

INSERT INTO  `medical`.`analyse` (`id`, `name`, `result`, `doctor_id`, `client_id`, `visit_id`)
VALUES (NULL ,  'blood analyse',  'you will life',  '2',  '1',  '3');
INSERT INTO  `medical`.`analyse` (`id`, `name`, `result`, `doctor_id`, `client_id`, `visit_id`)
VALUES (NULL ,  'MRI',  'you will life',  '1',  '1',  '1');

INSERT INTO  `medical`.`schedule` (`id`, `workday`, `beginworkday`, `endworkday`, `room`, `doctor_id`)
VALUES (NULL,  'monday',  '0',  '28800',  '213',  '1');
INSERT INTO  `medical`.`schedule` (`id`, `workday`, `beginworkday`, `endworkday`, `room`, `doctor_id`)
VALUES (NULL,  'thuesday',  '28800',  '57600',  '113',  '2');

INSERT INTO `medical`.`treatment` (`id`, `prescription`, `cure_count`, `method_of_using`, `cure_id`, `visit_id`)
VALUES (NULL, NULL, '1', '2 times a day', '1', '2');
INSERT INTO `medical`.`treatment` (`id`, `prescription`, `cure_count`, `method_of_using`, `cure_id`, `visit_id`)
VALUES (NULL, NULL, '1', '2 times a day', '2', '3');